version: "3.8"
services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vroomlegend
    networks:
      - db_network

  server-http:
    build:
      context: ./serverHTTP
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - db_network
    restart: always

  server-udp:
    build:
      context: ./serverUDP
    ports:
      - "6000:6000/udp"
    restart: always

networks:
  db_network:
    driver: bridge